### ISSUE TITLE
Use this for meteor 1.3.2 or use npm?

### ISSUE THREAD

**Issue by chrisco23** [rgnevashev/meteor-sparkpost#1]
Hi,

I'm in the process of moving from Mandrill to Sparkpost (as they recommend for people who don't need to pay for MailChimp).  Now that Meteor has provided npm support, does it make sense to use this package or something like https://www.npmjs.com/package/sparkpost ??

**Comment by rgnevashev** [comment]
I'm not moved  to 1.3 yet.. have experiment on your risk
This package for 1.2 only

**Comment by chrisco23** [comment]
ok, thanks.  For now I was able to get the npm working so closing.
